### PR TITLE
Adding shallow cloning for resourceListMeta in initialState

### PR DESCRIPTION
**Pull request by JPorry**

### CODE REVIEW

**Comment by jmeas** [comment]
Looks good – squash these into 1 commit and I'll merge :v:

**Comment by JPorry** [comment]
There you go!

**Comment by jmeas** [comment]
Thanks! Ok – last thing. Can you change the commit msg from "deep cloning" to "shallow cloning," since this isn't a deep clone. It's just a 1-level-more-deep shallow clone.

**Comment by JPorry** [comment]
Yeah, you are right! Done!

**Comment by jamesplease** [comment]
Looks good. Mergin'. Will cut a release soon. For the sake of safety, I'll be releasing this as a major bump (2.0.0), even though it's likely not going to break anyone's app.

**Pull request merged**
